"""
Monday.com Board Schemas and Column Definitions.
Maps Monday.com column IDs / titles to canonical field names.
"""

DEALS_COLUMN_MAPPING = {
    "Deal Name": "deal_name",
    "Owner code": "owner_code",
    "Client Code": "client_code",
    "Deal Status": "status",
    "Close Date (A)": "close_date",
    "Closure Probability": "closure_probability",
    "Masked Deal value": "deal_value",
    "Tentative Close Date": "tentative_close_date",
    "Deal Stage": "stage",
    "Product deal": "product",
    "Sector/service": "sector",
    "Created Date": "created_date",
}

WORK_ORDERS_COLUMN_MAPPING = {
    "Deal name masked": "deal_name",
    "Customer Name Code": "customer_code",
    "Serial #": "serial_no",
    "Nature of Work": "nature_of_work",
    "Last executed month of recurring project": "last_executed_month",
    "Execution Status": "execution_status",
    "Data Delivery Date": "data_delivery_date",
    "Date of PO/LOI": "po_date",
    "Document Type": "document_type",
    "Probable Start Date": "probable_start_date",
    "Probable End Date": "probable_end_date",
    "BD/KAM Personnel code": "owner_code",
    "Sector": "sector",
    "Type of Work": "type_of_work",
    "Is any Skylark software platform part of the client deliverables in this deal?": "software_platform",
    "Last invoice date": "last_invoice_date",
    "latest invoice no.": "latest_invoice_no",
    "Amount in Rupees (Excl of GST) (Masked)": "amount_excl_gst",
    "Amount in Rupees (Incl of GST) (Masked)": "amount_incl_gst",
    "Billed Value in Rupees (Excl of GST.) (Masked)": "billed_value_excl_gst",
    "Billed Value in Rupees (Incl of GST.) (Masked)": "billed_value_incl_gst",
    "Collected Amount in Rupees (Incl of GST.) (Masked)": "collected_amount_incl_gst",
    "Amount to be billed in Rs. (Exl. of GST) (Masked)": "amount_to_be_billed_excl_gst",
    "Amount to be billed in Rs. (Incl. of GST) (Masked)": "amount_to_be_billed_incl_gst",
    "Amount Receivable (Masked)": "amount_receivable",
    "AR Priority account": "ar_priority",
    "Quantity by Ops": "quantity_ops",
    "Quantities as per PO": "quantity_po",
    "Quantity billed (till date)": "quantity_billed",
    "Balance in quantity": "quantity_balance",
    "Invoice Status": "invoice_status",
    "Expected Billing Month": "expected_billing_month",
    "Actual Billing Month": "actual_billing_month",
    "Actual Collection Month": "actual_collection_month",
    "WO Status (billed)": "wo_status",
    "Collection status": "collection_status",
    "Collection Date": "collection_date",
    "Billing Status": "billing_status",
}
